"""Installation, deterministic manifest assembly and non-destructive migration."""
import json
from contextlib import closing
import os
from pathlib import Path
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import tomllib
from . import ROOT, MODULE, FEATURES, directory


def bootstrap():
    python = ROOT / '.venv' / ('Scripts/python.exe' if os.name == 'nt' else 'bin/python')
    if not python.exists():
        subprocess.run([sys.executable, '-m', 'venv', str(ROOT / '.venv')], check=True)
    subprocess.run([str(python), '-m', 'pip', 'install', '-r', str(ROOT / 'requirements.lock')], check=True)
    subprocess.run([str(python), '-m', 'pip', 'install', '--no-deps', '--no-build-isolation', '-e', str(ROOT)], check=True)
    npm = shutil.which('npm')
    if not npm:
        raise ValueError('Node.js 22.12+ and npm are required. Install them, then rerun bootstrap.')
    subprocess.run([npm, 'ci', '--ignore-scripts', '--omit=dev', '--no-audit', '--no-fund'], cwd=ROOT, check=True)
    return 0


def render(overrides=None):
    overrides = overrides or {}
    lines = ['# Generated by toolkit.py manifest; edit feature manifests, then regenerate.',
             'id = "kacper.toolkit"', 'name = "Luvus Toolkit"', 'version = "0.1.0"',
             'min_luvus_version = "0.13.4"', 'description = "Tasks, Git, agent launching, commands, usage and Keep Awake"',
             'platforms = ["macos", "linux", "windows"]']
    def table(kind, values):
        lines.extend(['', '[[' + kind + ']]'])
        lines.extend(key + ' = ' + json.dumps(value, ensure_ascii=False) for key, value in values.items())
    for python, platforms in [('python3', ['macos', 'linux']), ('python', ['windows'])]:
        table('build', {'platforms': platforms, 'command': [python, 'toolkit.py', 'bootstrap']})
        table('actions', {'id': 'doctor' + ('-windows' if python == 'python' else ''), 'title': 'Check Toolkit installation', 'platforms': platforms, 'command': [python, 'toolkit.py', 'doctor']})
    for feature in FEATURES:
        data = overrides.get(feature) or tomllib.loads((ROOT / 'features' / feature / 'luvus-module.toml').read_text())
        table('settings', {'key': feature + '-enabled', 'title': data['name'] + ': enabled', 'type': 'bool', 'default': True})
        for kind in ('settings', 'actions', 'panes', 'docks', 'bars', 'startup', 'events'):
            for original in data.get(kind, []):
                value = dict(original)
                if 'id' in value: value['id'] = feature + '-' + value['id']
                if 'key' in value: value['key'] = feature + '-' + value['key']
                if kind == 'settings': value['title'] = data['name'] + ': ' + value['title']
                argv = value.get('command')
                if argv and argv[1].endswith('tab_titles.py'):
                    continue  # One common focus hook replaces all six copies.
                if not argv:
                    table(kind, value)
                    continue
                target_platforms = value.get('platforms', ['macos', 'linux', 'windows'])
                if argv[0] == 'python':
                    target_platforms = ['windows']
                for python, platforms in [('python3', ['macos', 'linux']), ('python', ['windows'])]:
                    supported = [p for p in platforms if p in target_platforms]
                    if not supported: continue
                    entry = dict(value, platforms=supported, command=[python, 'toolkit.py', 'run', feature, *argv[1:]])
                    # Entries without their own Windows variant need unique IDs.
                    if python == 'python' and len(target_platforms) > 1 and 'id' in entry:
                        entry['id'] += '-windows'
                    table(kind, entry)
    for python, platforms in [('python3', ['macos', 'linux']), ('python', ['windows'])]:
        table('events', {'on': 'pane.focused', 'platforms': platforms, 'command': [python, 'toolkit_core/tab_titles.py']})
    return '\n'.join(lines) + '\n'


def manifest():
    text = render()
    parsed = tomllib.loads(text)
    for kind in ('actions', 'panes', 'docks', 'bars', 'settings'):
        key = 'key' if kind == 'settings' else 'id'
        values = [v[key] for v in parsed.get(kind, [])]
        if len(values) != len(set(values)): raise ValueError('Duplicate ' + kind)
    (ROOT / 'luvus-module.toml').write_text(text)
    (ROOT / 'toolkit_core/catalog.json').write_text(json.dumps({kind: [v['id'] for v in parsed.get(kind, [])] for kind in ('actions','panes','bars','docks')}, indent=2) + '\n')
    return 0


def doctor():
    checks = {'python': sys.version.split()[0], 'node': shutil.which('node'), 'npm': shutil.which('npm'), 'git': shutil.which('git'), 'luvus': os.environ.get('LUVUS_BIN_PATH') or shutil.which('luvus')}
    if checks['node']:
        checks['node_version'] = subprocess.check_output([checks['node'], '--version'], text=True).strip()
        version = tuple(int(p) for p in checks['node_version'].lstrip('v').split('.'))
        if version < (22, 12, 0): raise ValueError('Node.js 22.12+ is required')
    for dep in ('textual', 'psutil', 'keyring'):
        __import__(dep)
    print(json.dumps(checks, indent=2))
    return 0 if all(checks.values()) else 1



def migrated_bytes(path):
    """Rewrite only recognized standalone Launcher bridges; preserve custom argv."""
    raw = path.read_bytes()
    if path.name != 'projects.json': return raw
    data = json.loads(raw)
    providers = data.get('providers', {}) if isinstance(data, dict) else {}
    changed = False
    python = str(ROOT / '.venv' / ('Scripts/python.exe' if os.name == 'nt' else 'bin/python'))
    dispatcher = str(ROOT / 'toolkit.py')
    def standalone(argv, feature, script):
        if not isinstance(argv, list) or len(argv) < 2: return False
        source = Path(argv[1])
        expected = source.parent / '.venv' / ('Scripts/python.exe' if os.name == 'nt' else 'bin/python')
        return source.name == script and source.parent.name == 'luvus-' + feature and Path(argv[0]) == expected
    tasks = providers.get('tasks')
    if (standalone(tasks, 'tasks', 'launcher.py') and len(tasks) == 4 and tasks[2] == 'bundle-api'
            and Path(tasks[3]) == path.parent.parent / FEATURES['tasks']):
        providers['tasks'] = [python, dispatcher, 'run', 'tasks', 'launcher.py', 'bundle-api', str(directory('tasks'))]
        changed = True
    commands = providers.get('commands')
    if (standalone(commands, 'cli-launcher', 'commands_adapter.py') and len(commands) == 7
            and standalone(commands[2:], 'project-commands', 'launcher.py') and commands[4:6] == ['api', '--store']
            and Path(commands[6]) == path.parent.parent / FEATURES['project-commands']):
        providers['commands'] = [python, str(ROOT / 'features/cli-launcher/commands_adapter.py'),
                                python, dispatcher, 'run', 'project-commands', 'launcher.py', 'api', '--store', str(directory('project-commands'))]
        changed = True
    return (json.dumps(data, indent=2) + '\n').encode() if changed else raw


def migrate():
    """Preview first; copy durable state without overwriting conflicts."""
    import hashlib
    apply = '--apply' in sys.argv
    home = Path((os.environ.get('LUVUS_HOME') or str(Path.home() / '.luvus')))
    moves = []
    excluded = {'worktrees', 'sessions', 'tab-titles', '__pycache__', '.git'}
    combined = {}
    def fingerprint(path):
        digest = hashlib.sha256()
        if path.suffix in ('.sqlite', '.sqlite3', '.db'):
            with closing(sqlite3.connect(path.as_uri() + '?mode=ro', uri=True)) as db:
                for line in db.iterdump(): digest.update(line.encode())
        else:
            digest.update(migrated_bytes(path))
        return digest.hexdigest()
    for feature, old in FEATURES.items():
        source = home / 'modules/config' / old
        preferences = source / 'settings.json'
        if preferences.exists():
            values = json.loads(preferences.read_text())
            if not isinstance(values, dict): raise ValueError('Invalid source settings: ' + str(preferences))
            combined.update({feature + '-' + key: value for key, value in values.items()})
        if not source.exists(): continue
        for current, dirs, files in os.walk(source, followlinks=False):
            dirs[:] = [d for d in dirs if d not in excluded and not (Path(current) / d).is_symlink()]
            for filename in files:
                path = Path(current) / filename
                rel = path.relative_to(source)
                if path.is_symlink(): raise ValueError('Migration refuses symlink: ' + str(path))
                if path.suffix in ('.lock', '.log', '.tmp') or path.name.endswith(('-wal', '-shm')): continue
                target = directory(feature) / rel
                if target.exists():
                    if fingerprint(target) != fingerprint(path):
                        raise ValueError('Migration conflict; destination left unchanged: ' + str(target))
                    continue
                moves.append((path, target))
        if feature == 'ai-usage':
            # The restoration record is durable even though old releases stored it in state.
            source_backup = home / 'modules/state' / old / 'claude-statusline-backup.json'
            target_backup = directory(feature, 'state') / source_backup.name
            if source_backup.exists():
                if target_backup.exists() and fingerprint(source_backup) != fingerprint(target_backup):
                    raise ValueError('Conflicting Claude restoration backup')
                if not target_backup.exists(): moves.append((source_backup, target_backup))
    settings_path = directory('tasks').parents[1] / 'settings.json'
    existing = json.loads(settings_path.read_text()) if settings_path.exists() else {}
    for key, value in combined.items():
        if key in existing and existing[key] != value:
            raise ValueError('Conflicting Toolkit setting: ' + key)
    combined = {**existing, **combined}
    print(json.dumps({'apply': apply, 'copies': [{'from': str(a), 'to': str(b)} for a,b in moves], 'settings_keys': sorted(combined)}, indent=2))
    if not apply: return 0
    for source, target in moves:
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        fd, temporary = tempfile.mkstemp(dir=target.parent)
        os.close(fd)
        try:
            if source.suffix in ('.sqlite', '.sqlite3', '.db'):
                with closing(sqlite3.connect(source.as_uri() + '?mode=ro', uri=True)) as src, closing(sqlite3.connect(temporary)) as dst:
                    src.backup(dst)
            else: Path(temporary).write_bytes(migrated_bytes(source))
            os.link(temporary, target)
        finally: os.unlink(temporary)
    if combined and combined != existing:
        settings_path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        # Hold the same native lock for toolkit migration processes. External edits
        # are detected before replacement; native workers must be disabled at cutover.
        from .locks import acquire
        with settings_path.with_suffix('.migration.lock').open('a+b') as lock:
            acquire(lock)
            current = json.loads(settings_path.read_text()) if settings_path.exists() else {}
            if current != existing: raise ValueError('Settings changed during migration; retry')
            fd, temporary = tempfile.mkstemp(dir=settings_path.parent)
            try:
                with os.fdopen(fd, 'w') as stream: json.dump(combined, stream, indent=2)
                os.replace(temporary, settings_path)
            finally:
                if os.path.exists(temporary): os.unlink(temporary)
    return 0
